# Generated by Django 3.2.8 on 2021-11-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
