# Generated by Django 3.2.8 on 2021-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_alter_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
